# Generated by Django 4.0.3 on 2022-04-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeModel',
            new_name='Recipe',
        ),
    ]
