# Generated by Django 4.0.3 on 2022-04-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_recipemodel_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
